### ISSUE TITLE
github bots could help workflows

### ISSUE THREAD

**Issue by vbatts** [opencontainers/image-spec#598]
https://github.com/icecrime/poule is an option

**Comment by erikh** [comment]
Ideas:

* reminder features for when things are inactive for a while
* "discuss this item" -> label a ticket for the next agenda meeting

**Comment by erikh** [comment]
* bot requires PRs reference open issues

**Comment by erikh** [comment]
* bot auto-closes issues that have not seen discussion in X time

**Comment by erikh** [comment]
@vbatts https://github.com/icecrime/poule/pull/42 should resolve the discuss-this-item and reference-open-issues agenda items but it will still need a patch to implement comment-based reminders.

**Comment by erikh** [comment]
Here's a poule.yml that can satisfy most of the issues (more below)

```yaml
---
operations:
  - type: label
    filters: {
        ~labels: [ "discuss" ],
        contains: [ "(?:^|\\n)#discuss(?:$|\\n)" ],
    }
    settings: {
        patterns: {
          discuss:  [ ".*" ],
        }
    }
  - type: prune 
    filters: {
      labels: [ "needs-reference" ],
      age: "1w",
    }
    settings: {
      action: close,
      grace-period: "1d",
      outdated-threshold: "1d",
    }
  - type: prune
    filters: {
      ~labels: [ "discuss" ],
      age: "2w",
    }
    settings: {
      action: ping,
      grace-period: "1m",
      outdated-threshold: "2w",
    }
```

To run this effectively you will need a fork of icecrime/poule I made over at erikh/poule, oci-integration branch. To build and run:

```
# PREFIX= is optional; the default is shown here
$ make && sudo make PREFIX=/usr/local install
$ poule --dry-run --repository opencontainers/image-spec --token $GITHUB_TOKEN batch poule.yml
```

This should not make any modifications to the repository's issues or PRs, just tell you what it will do.

Information about the rules:

* Commenting with `#discuss` on its own line will tag the issue with `discuss`. I will build another tool to mail this information out to the list prior to the meetings.
* Issues that aren't tagged with discuss and open for more than 2w get alerted, after 4w they get closed.
* Any issue can be manually tagged with `needs-references` to give it a shorter expiry than the default; poule will still need some tooling here to negate matches before this can be fully automated.

PTAL and comments are very welcome.
